import type { Company } from "@/lib/interfaces/types";

export const COMPANIES: Company[] = [
  {
    id: "meridian-fish",
    name: "Meridian Fisheries International",
    ticker: "MRDN",
    description: "Global leader in premium sustainable fishing and aquaculture",
    ceoName: "Björn Halvorsen",
    headquarters: { city: "Bergen", country: "Norway" },
    sectors: [
      { sectorId: "agriculture", weight: 0.7 },
      { sectorId: "shipping", weight: 0.3 },
    ],
    baseValue: 45,
    volatilityMultiplier: 1.2,
    founded: "1987",
    employees: 12000,
    funFact: "Their CEO once arm-wrestled a tuna and won",
  },
  {
    id: "aurum-dynamics",
    name: "Aurum Dynamics",
    ticker: "AURM",
    description: "Vertically integrated gold mining and refining",
    ceoName: "Margaret Okonkwo",
    headquarters: { city: "Johannesburg", country: "South Africa" },
    sectors: [
      { sectorId: "mining", weight: 0.9 },
      { sectorId: "finance", weight: 0.1 },
    ],
    baseValue: 120,
    volatilityMultiplier: 0.8,
    founded: "1952",
    employees: 35000,
    funFact: "Company mascot is a golden retriever named 'Bullion'",
  },
  {
    id: "nexgen-ai",
    name: "NexGen AI Solutions",
    ticker: "NXGN",
    description: "Enterprise AI and machine learning platforms",
    ceoName: "Priya Patel",
    headquarters: { city: "Bangalore", country: "India" },
    sectors: [{ sectorId: "tech", weight: 1.0 }],
    baseValue: 230,
    volatilityMultiplier: 1.5,
    founded: "2015",
    employees: 8500,
    funFact: "Their chatbot once accidentally ordered 10,000 pizzas",
  },
  {
    id: "petrovolt-energy",
    name: "PetroVolt Energy",
    ticker: "PVLT",
    description: "Oil & gas exploration with a growing renewables division",
    ceoName: "Viktor Petrov",
    headquarters: { city: "Houston", country: "United States" },
    sectors: [{ sectorId: "energy", weight: 1.0 }],
    baseValue: 88,
    volatilityMultiplier: 1.0,
    founded: "1974",
    employees: 42000,
    funFact: "Still has a functional oil derrick in the office lobby",
  },
  {
    id: "ironclad-defense",
    name: "Ironclad Defense Systems",
    ticker: "IRND",
    description: "Advanced military technology and cybersecurity",
    ceoName: "James Thornton",
    headquarters: { city: "London", country: "United Kingdom" },
    sectors: [
      { sectorId: "defense", weight: 0.8 },
      { sectorId: "tech", weight: 0.2 },
    ],
    baseValue: 165,
    volatilityMultiplier: 0.6,
    founded: "1961",
    employees: 28000,
    funFact: "Their original product was an unbreakable umbrella",
  },
  {
    id: "luxe-monde",
    name: "Luxe Monde Holdings",
    ticker: "LUXE",
    description: "Luxury fashion, accessories, and lifestyle brands",
    ceoName: "Isabella Castellano",
    headquarters: { city: "Milan", country: "Italy" },
    sectors: [{ sectorId: "luxury", weight: 1.0 }],
    baseValue: 310,
    volatilityMultiplier: 0.7,
    founded: "1923",
    employees: 19000,
    funFact: "Their flagship store has a champagne fountain that actually works",
  },
  {
    id: "pacific-shipping",
    name: "Pacific Horizon Logistics",
    ticker: "PCHL",
    description: "Container shipping and global freight management",
    ceoName: "Chen Wei",
    headquarters: { city: "Singapore", country: "Singapore" },
    sectors: [{ sectorId: "shipping", weight: 1.0 }],
    baseValue: 72,
    volatilityMultiplier: 0.9,
    founded: "1998",
    employees: 15000,
    funFact: "Lost a container of rubber ducks in 2019; still finding them on beaches",
  },
  {
    id: "titan-bank",
    name: "Titan Global Bank",
    ticker: "TITN",
    description: "International banking and wealth management",
    ceoName: "Hans Müller",
    headquarters: { city: "Zurich", country: "Switzerland" },
    sectors: [{ sectorId: "finance", weight: 1.0 }],
    baseValue: 195,
    volatilityMultiplier: 0.5,
    founded: "1889",
    employees: 55000,
    funFact: "Their vault door weighs more than a blue whale",
  },
  {
    id: "stellar-entertainment",
    name: "Stellar Entertainment Group",
    ticker: "STLR",
    description: "Film studios, streaming, and theme parks",
    ceoName: "Sofia Rivera",
    headquarters: { city: "Los Angeles", country: "United States" },
    sectors: [
      { sectorId: "entertainment", weight: 0.8 },
      { sectorId: "tech", weight: 0.2 },
    ],
    baseValue: 140,
    volatilityMultiplier: 1.1,
    founded: "2003",
    employees: 22000,
    funFact: "Their CEO does all her own stunts at shareholder meetings",
  },
  {
    id: "greenfield-agri",
    name: "Greenfield Agricultural Corp",
    ticker: "GRFL",
    description: "Large-scale farming and organic food production",
    ceoName: "Eduardo Santos",
    headquarters: { city: "São Paulo", country: "Brazil" },
    sectors: [{ sectorId: "agriculture", weight: 1.0 }],
    baseValue: 55,
    volatilityMultiplier: 0.8,
    founded: "1965",
    employees: 30000,
    funFact: "Their CEO can identify 200 types of soil by taste",
  },
  {
    id: "rare-earth-intl",
    name: "Rare Earth International",
    ticker: "RARE",
    description: "Mining and processing of rare earth elements",
    ceoName: "Mei Tanaka",
    headquarters: { city: "Tokyo", country: "Japan" },
    sectors: [
      { sectorId: "mining", weight: 0.7 },
      { sectorId: "tech", weight: 0.3 },
    ],
    baseValue: 98,
    volatilityMultiplier: 1.3,
    founded: "2008",
    employees: 11000,
    funFact: "Named after the minerals, not a commentary on their stock availability",
  },
  {
    id: "voltaic-motors",
    name: "Voltaic Motors",
    ticker: "VOLT",
    description: "Electric vehicles and battery technology",
    ceoName: "Astrid Lindström",
    headquarters: { city: "Stockholm", country: "Sweden" },
    sectors: [
      { sectorId: "tech", weight: 0.5 },
      { sectorId: "energy", weight: 0.5 },
    ],
    baseValue: 175,
    volatilityMultiplier: 1.4,
    founded: "2012",
    employees: 16000,
    funFact: "Their first prototype was powered by hamster wheels",
  },
  {
    id: "sahara-oil",
    name: "Sahara Oil & Gas",
    ticker: "SHRA",
    description: "African oil exploration and production",
    ceoName: "Amara Okafor",
    headquarters: { city: "Lagos", country: "Nigeria" },
    sectors: [{ sectorId: "energy", weight: 1.0 }],
    baseValue: 62,
    volatilityMultiplier: 1.1,
    founded: "1991",
    employees: 18000,
    funFact: "Found oil while looking for a lost company picnic frisbee",
  },
  {
    id: "fortress-insurance",
    name: "Fortress Global Insurance",
    ticker: "FTRS",
    description: "Commercial and personal insurance worldwide",
    ceoName: "Liam O'Brien",
    headquarters: { city: "Dublin", country: "Ireland" },
    sectors: [{ sectorId: "finance", weight: 1.0 }],
    baseValue: 82,
    volatilityMultiplier: 0.4,
    founded: "1946",
    employees: 25000,
    funFact: "Will insure anything except their own Christmas party",
  },
  {
    id: "nova-pharma",
    name: "Nova Pharmaceutical",
    ticker: "NOVA",
    description: "Drug discovery and biotechnology",
    ceoName: "Nadia Al-Rashid",
    headquarters: { city: "Geneva", country: "Switzerland" },
    sectors: [
      { sectorId: "tech", weight: 0.4 },
      { sectorId: "luxury", weight: 0.1 },
      { sectorId: "agriculture", weight: 0.5 },
    ],
    baseValue: 210,
    volatilityMultiplier: 1.2,
    founded: "2001",
    employees: 9500,
    funFact: "Accidentally invented a cure for hiccups while testing shampoo",
  },
];

export function getCompany(id: string): Company | undefined {
  return COMPANIES.find((c) => c.id === id);
}

export function getCompanyByTicker(ticker: string): Company | undefined {
  return COMPANIES.find((c) => c.ticker === ticker);
}

export function getCompaniesBySector(sectorId: string): Company[] {
  return COMPANIES.filter((c) =>
    c.sectors.some((s) => s.sectorId === sectorId),
  );
}
